### ISSUE TITLE
Scope blame also annotates lines not in the diff of the PR

### ISSUE THREAD

**Issue by lode** [tinovyatkin/action-php-codesniffer#41]
I'm using the default `scope: blame` which seems to also annotate lines which are not touched in the current PR. Is this is shortcoming of the current `run-on-blame.ts` code or should it actually only work on diff lines?

**Comment by tinovyatkin** [comment]
Sounds like a bug, not sure whether in this library or underlying `git-blame-json`. Can you describe any particular case to understand where to dig to?

**Comment by lode** [comment]
I can try to set up a demo repo.

**Comment by lode** [comment]
See https://github.com/lode/phpcs-action-test/pull/1. It annotates lines outside the diff of the PR.

**Comment by tinovyatkin** [comment]
@lode Is this `phpcs.xml` respected when you run codesniffer locally?

**Comment by tinovyatkin** [comment]
@lode you probably confused by `diff` and `blame`. Blame scope can be bigger than diff scope - that all lines last changed by the author of current PR.

**Comment by lode** [comment]
Yeah indeed. I wasn't sure, I thought it would sort of combine the lines from the commit it was checking with blame.
